import connectToDatabase from "@/lib/mongodb";
import License from "@/lib/models/License";
import Admin from "@/lib/models/Admin";
import { Key, Users, AlertOctagon, DollarSign, ShieldAlert } from "lucide-react";
import { cookies } from "next/headers";
import { verifyAdminToken } from "@/lib/jwt";

async function getAuthUsername() {
  const cookieStore = await cookies();
  const token = cookieStore.get('admin_token')?.value;
  if (!token) return 'Admin';
  const decoded = verifyAdminToken(token);
  return decoded ? decoded.username : 'Admin';
}

async function getStats() {
  try {
    await connectToDatabase();
    const licenses = await License.find();
    const admins = await Admin.find({}, 'username');
    
    // Aggregate by admin
    const adminCounts: Record<string, number> = {};
    
    // Initialize all admins with 0 keys
    admins.forEach(admin => {
      adminCounts[admin.username] = 0;
    });

    let totalKeys = licenses.length;
    let totalUsed = 0;
    let totalBanned = 0;
    let totalRevenue = 0;

    licenses.forEach((lic) => {
      const creator = lic.createdBy || 'unknown';
      adminCounts[creator] = (adminCounts[creator] || 0) + 1;

      if (lic.deviceId) totalUsed++;
      if (lic.status === 'banned') totalBanned++;

      const durationMs = new Date(lic.expiresAt).getTime() - new Date(lic.createdAt).getTime();
      const days = Math.round(durationMs / (1000 * 60 * 60 * 24));
      
      let price = 0;
      if (days <= 7) price = 499;
      else if (days <= 15) price = 1499;
      else price = 1999;

      totalRevenue += price;
    });

    const adminStatsArray = Object.entries(adminCounts)
      .map(([username, count]) => ({ username, count }))
      .sort((a, b) => b.count - a.count);

    return { 
      status: "Connected",
      totalKeys,
      totalUsed,
      totalBanned,
      totalRevenue,
      adminStatsArray
    };
  } catch (error) {
    console.error(error);
    return { status: "Error connecting to DB", totalKeys: 0, totalUsed: 0, totalBanned: 0, totalRevenue: 0, adminStatsArray: [] };
  }
}

export default async function AdminDashboard() {
  const stats = await getStats();
  const currentUsername = await getAuthUsername();

  return (
    <div className="admin-page space-y-6 md:space-y-8">
      <div className="admin-page-header">
        <div>
          <p className="admin-eyebrow">Admin dashboard</p>
          <h1 className="admin-title">Overview</h1>
          <p className="admin-subtitle">Welcome back, <span className="font-black text-[#7B5EA7]">{currentUsername}</span>. Real-time statistics are loaded.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard title="Total Keys" value={stats.totalKeys.toString()} icon={<Key className="text-[#7B5EA7]" size={22} />} color="#7B5EA7" />
        <StatCard title="Used Devices" value={stats.totalUsed.toString()} icon={<Users className="text-[#007AFF]" size={22} />} color="#007AFF" />
        <StatCard title="Banned Keys" value={stats.totalBanned.toString()} icon={<AlertOctagon className="text-[#FF3B30]" size={22} />} negative={stats.totalBanned > 0} color="#FF3B30" />
        <StatCard title="Total Revenue" value={`₹${stats.totalRevenue.toLocaleString()}`} icon={<DollarSign className="text-[#34C759]" size={22} />} color="#34C759" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-8">
        {/* Admin Key Generation Stats */}
        <div className="admin-panel p-5 md:p-7">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-[#7B5EA7]/10 rounded-2xl text-[#7B5EA7]">
              <ShieldAlert size={24} />
            </div>
            <div>
              <h3 className="text-xl font-black text-slate-900">Admin Activity</h3>
              <p className="text-sm text-slate-500 font-medium">Keys generated by each admin</p>
            </div>
          </div>
          
          <div className="space-y-4 mt-4">
            {stats.adminStatsArray.length > 0 ? (
              stats.adminStatsArray.map((admin, idx) => (
                <div key={idx} className="admin-card flex justify-between items-center p-4 bg-slate-50/80">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#7B5EA7] to-[#9B7FBF] text-white flex items-center justify-center font-black shadow-sm">
                      {admin.username.charAt(0).toUpperCase()}
                    </div>
                    <span className="font-bold text-slate-700">{admin.username}</span>
                  </div>
                  <div className="flex flex-col items-end">
                    <span className="text-lg font-black text-slate-900">{admin.count}</span>
                    <span className="text-xs text-slate-500 font-medium">Keys</span>
                  </div>
                </div>
              ))
            ) : (
              <p className="text-sm text-slate-500 text-center py-4">No keys generated yet.</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({ title, value, icon, negative = false, color = "#007AFF" }: { title: string, value: string, icon: React.ReactNode, negative?: boolean, color?: string }) {
  const shadowColor = `${color}25`;
  
  return (
    <div 
      className="admin-card bg-white p-4 relative overflow-hidden group min-h-[118px] flex flex-col justify-center cursor-default"
      style={{ boxShadow: `0 8px 24px -8px ${shadowColor}` }}
    >
      <div className="absolute inset-x-0 top-0 h-1.5" style={{ background: color }} />
      
      <div className="relative z-10 flex items-center justify-between">
        <div>
          <h4 className="text-slate-500 font-black text-[10px] sm:text-xs mb-1 uppercase tracking-wide">{title}</h4>
          <p className={`text-2xl sm:text-3xl font-black tracking-tight ${negative ? 'text-red-500' : 'text-slate-800'}`}>
            {value}
          </p>
        </div>
        <div className="p-2.5 bg-slate-50 rounded-xl border border-slate-100 group-hover:shadow-md transition-all">
          {icon}
        </div>
      </div>
    </div>
  );
}


