import connectToDatabase from "@/lib/mongodb";
import License from "@/lib/models/License";
import Admin from "@/lib/models/Admin";
import { Key, Users, AlertOctagon, DollarSign, ShieldAlert } from "lucide-react";
import { cookies } from "next/headers";
import { verifyAdminToken } from "@/lib/jwt";

async function getAuthUsername() {
  const cookieStore = await cookies();
  const token = cookieStore.get('admin_token')?.value;
  if (!token) return 'Admin';
  const decoded = verifyAdminToken(token);
  return decoded ? decoded.username : 'Admin';
}

async function getStats() {
  try {
    await connectToDatabase();
    const licenses = await License.find();
    const admins = await Admin.find({}, 'username');
    
    // Aggregate by admin
    const adminCounts: Record<string, number> = {};
    
    // Initialize all admins with 0 keys
    admins.forEach(admin => {
      adminCounts[admin.username] = 0;
    });

    let totalKeys = licenses.length;
    let totalUsed = 0;
    let totalBanned = 0;
    let totalRevenue = 0;

    licenses.forEach((lic) => {
      const creator = lic.createdBy || 'unknown';
      adminCounts[creator] = (adminCounts[creator] || 0) + 1;

      if (lic.deviceId) totalUsed++;
      if (lic.status === 'banned') totalBanned++;

      const durationMs = new Date(lic.expiresAt).getTime() - new Date(lic.createdAt).getTime();
      const days = Math.round(durationMs / (1000 * 60 * 60 * 24));
      
      let price = 0;
      if (days <= 7) price = 499;
      else if (days <= 15) price = 1499;
      else price = 1999;

      totalRevenue += price;
    });

    const adminStatsArray = Object.entries(adminCounts)
      .map(([username, count]) => ({ username, count }))
      .sort((a, b) => b.count - a.count);

    return { 
      status: "Connected",
      totalKeys,
      totalUsed,
      totalBanned,
      totalRevenue,
      adminStatsArray
    };
  } catch (error) {
    console.error(error);
    return { status: "Error connecting to DB", totalKeys: 0, totalUsed: 0, totalBanned: 0, totalRevenue: 0, adminStatsArray: [] };
  }
}

export default async function AdminDashboard() {
  const stats = await getStats();
  const currentUsername = await getAuthUsername();

  return (
    <div className="max-w-6xl mx-auto space-y-6 md:space-y-8">
      <div>
        <h1 className="text-2xl sm:text-3xl lg:text-4xl font-black text-slate-900 tracking-tight">Overview</h1>
        <p className="text-xs sm:text-sm md:text-base text-slate-500 mt-1 font-medium">Welcome back, <span className="font-bold text-blue-600">{currentUsername}</span>. Real-time statistics are loaded.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard title="Total Keys" value={stats.totalKeys.toString()} icon={<Key className="text-blue-600" size={24} />} color="#007AFF" />
        <StatCard title="Used Devices" value={stats.totalUsed.toString()} icon={<Users className="text-purple-600" size={24} />} color="#AF52DE" />
        <StatCard title="Banned Keys" value={stats.totalBanned.toString()} icon={<AlertOctagon className="text-red-600" size={24} />} negative={stats.totalBanned > 0} color="#FF3B30" />
        <StatCard title="Total Revenue" value={`₹${stats.totalRevenue.toLocaleString()}`} icon={<DollarSign className="text-emerald-500" size={24} />} color="#34C759" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-8">
        {/* Admin Key Generation Stats */}
        <div className="bg-white rounded-[28px] p-6 md:p-8 border border-white shadow-xl">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-blue-50 rounded-2xl text-blue-600">
              <ShieldAlert size={24} />
            </div>
            <div>
              <h3 className="text-xl font-black text-slate-900">Admin Activity</h3>
              <p className="text-sm text-slate-500 font-medium">Keys generated by each admin</p>
            </div>
          </div>
          
          <div className="space-y-4 mt-4">
            {stats.adminStatsArray.length > 0 ? (
              stats.adminStatsArray.map((admin, idx) => (
                <div key={idx} className="flex justify-between items-center p-4 bg-slate-50 rounded-2xl border border-slate-100 hover:border-blue-100 transition-colors">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-blue-500 to-purple-500 text-white flex items-center justify-center font-bold">
                      {admin.username.charAt(0).toUpperCase()}
                    </div>
                    <span className="font-bold text-slate-700">{admin.username}</span>
                  </div>
                  <div className="flex flex-col items-end">
                    <span className="text-lg font-black text-slate-900">{admin.count}</span>
                    <span className="text-xs text-slate-500 font-medium uppercase tracking-wider">Keys</span>
                  </div>
                </div>
              ))
            ) : (
              <p className="text-sm text-slate-500 text-center py-4">No keys generated yet.</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({ title, value, icon, negative = false, color = "#007AFF" }: { title: string, value: string, icon: React.ReactNode, negative?: boolean, color?: string }) {
  const blobColor = `${color}15`;
  const blobColor2 = `${color}08`;
  const shadowColor = `${color}25`;
  
  return (
    <div 
      className="bg-white rounded-2xl p-4 border border-slate-100 hover:border-transparent transition-all relative overflow-hidden group min-h-[110px] flex flex-col justify-center cursor-default"
      style={{ boxShadow: `0 8px 24px -8px ${shadowColor}` }}
    >
      {/* Decorative Blobs */}
      <div 
        className="absolute -top-8 -right-8 w-24 h-24 rounded-full pointer-events-none transition-transform duration-500 group-hover:scale-125" 
        style={{ background: blobColor }}
      />
      <div 
        className="absolute -bottom-6 -left-6 w-20 h-20 rounded-full pointer-events-none transition-transform duration-500 group-hover:scale-110" 
        style={{ background: blobColor2 }}
      />
      
      <div className="relative z-10 flex items-center justify-between">
        <div>
          <h4 className="text-slate-400 font-bold text-[10px] sm:text-xs uppercase tracking-wider mb-0.5">{title}</h4>
          <p className={`text-2xl sm:text-3xl font-black tracking-tight ${negative ? 'text-red-500' : 'text-slate-800'}`}>
            {value}
          </p>
        </div>
        <div className="p-2.5 bg-white rounded-xl shadow-sm border border-slate-50 group-hover:shadow-md transition-all">
          {icon}
        </div>
      </div>
    </div>
  );
}


